# Generated by Django 4.2.3 on 2023-07-27 11:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0002_rename_question_question_question_details'),
    ]

    operations = [
        migrations.RenameField(
            model_name='favoritequestion',
            old_name='question_id',
            new_name='question',
        ),
        migrations.RenameField(
            model_name='favoritequestion',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='readquestion',
            old_name='question_id',
            new_name='question',
        ),
        migrations.RenameField(
            model_name='readquestion',
            old_name='user_id',
            new_name='user',
        ),
    ]
