# Generated by Django 4.2.3 on 2023-07-27 12:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0003_rename_question_id_favoritequestion_question_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='question_details',
            new_name='question',
        ),
    ]
