# Generated by Django 4.2.3 on 2023-07-26 20:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_rename_idname_user_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='name',
            new_name='username',
        ),
    ]
