# Generated by Django 4.2.3 on 2023-07-26 20:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_rename_name_user_username'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='display_name',
            new_name='full_name',
        ),
    ]
